-- Migration to add Mercado Pago fields to pix_payments table
ALTER TABLE pix_payments 
ADD COLUMN IF NOT EXISTS mercadopago_id TEXT,
ADD COLUMN IF NOT EXISTS mercadopago_status TEXT,
ADD COLUMN IF NOT EXISTS mercadopago_payment_method TEXT;

-- Add index for search by mercadopago_id
CREATE INDEX IF NOT EXISTS idx_pix_payments_mercadopago_id ON pix_payments(mercadopago_id);

COMMENT ON COLUMN pix_payments.mercadopago_id IS 'ID generated by Mercado Pago for the transaction';
COMMENT ON COLUMN pix_payments.mercadopago_status IS 'Current status of the payment in Mercado Pago';
COMMENT ON COLUMN pix_payments.mercadopago_payment_method IS 'Payment method used in Mercado Pago (e.g. account_money, pix, credit_card)';
